DROP DATABASE IF EXISTS CH02;
CREATE DATABASE CH02;

DROP DATABASE IF EXISTS CH03_METADATAXMLJPA;
DROP DATABASE IF EXISTS CH03_METAMODEL;
CREATE DATABASE CH03_METADATAXMLJPA;
CREATE DATABASE CH03_METAMODEL;